baseURL = "/"
relativeurls = true
languageCode = "en-us"
title = "Piyayut Chitchumnong"
theme = "minimal"
disqusShortname = "piyayutch" # delete this to disable disqus comments
# googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$", ".ipynb_checkpoints"]


[params]
    author = "Piyayut Chitchumnong"
    description = "Economist & Data Scientist"
    githubUsername = "piyayut-ch"
    accent = "royalblue"
    showBorder = true
    backgroundColor = "snow"
    font = "Prompt" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "zenburn"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift", "r"]

[markup]
  defaultMarkdownHandler = "pandoc"
  [markup.tableOfContents]
    endLevel = 2
    ordered = false
    startLevel = 1
    
[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 3

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:piyayut.ch@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/piyayut-ch/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/piyayutch/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/username/"
    name = "linkedin"
    weight = 4

[[menu.icon]]
    url = "https://www.stackoverflow.com/username/"
    name = "stack-overflow"
    weight = 5
