---
title: "แนะนำ R package tsbox จัดการข้อมูลอนุกรมเวลา"
author: "ปิยยุทธ จิตต์จำนงค์"
date: "2020-05-20"
lastmod: "2020-05-20"
categories: ["R"]
tags: ["R", "tsbox", "Rpackage", "tips", "time series"]
showtoc: true
autoCollapseToc: true
contentCopyright: MIT
draft: true
mathjax: true
---

## เกริ่น {#intro}



```{r}
install.packages("tsbox")
```

## การแปลงข้อมูล
เราสามารถใช้ `tsbox` เปลี่ยนแปลง class ของข้อมูลอนุกรมเวลาได้ ตามความต้องการ class ที่รองรับ ได้แก่ `ts`, `xts`, `data.frame`, `data.table`, `tibble`, `zoo`, `tsibble`, `tibbletime`, `timeSeries`, `irts` และ `tis`

```{r}
library(tsbox)
x.ts = ts_c(fdeaths, mdeaths) #ts
x.xts = ts_xts(x.ts) #xts
x.df = ts_df(x.xts) #data.frame
x.dt = ts_dt(x.df) #data.table
x.tbl = ts_tbl(x.dt) #tibble
x.zoo = ts_zoo(x.tbl) #zoo
x.tsibble = ts_tsibble(x.zoo) #tsibble
x.irts = ts_irts(x.tsibble)

all.equal(ts_ts(x.tsibble), x.ts) #ทดสอบว่า object ทั้งสองเท่ากันหรือไม่
# x.tibbletime = ts_tibbletime(x.tsibble) #tibbletime
# x.timeSeries = ts_timeSeries(x.tibbletime) #timeSeries
# x.irts = ts_irts(x.tibbletime) #irts
# x.tis = ts_tis(x.irts) #tis
```

```{r}
options(repr.plot.width=8, repr.plot.height=4, repr.plot.res = 300)
```

```{r}
ts_plot(mdeaths, austres) 
```

```{r}
ts_ggplot(mdeaths, austres)
```

```{r}
ts_summary(ts_c(mdeaths, austres))
```

```{r}
ts_scale(x.xts)
```

```{r}
ts_seas(mdeaths)
```

```{r}
x = ts_trend(mdeaths)
```

```{r}
str(x)
```

```{r}
ts_frequency(mdeaths, 'year')
```

```{r}
x.df
```

```{r}

```
